services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Provider\Domain\Service\Brand\BrandLifecycleServiceCollection:
#    public: true
#
#  provider.lifecycle.brand.service_collection: '@Ivoz\Provider\Domain\Service\Brand\BrandLifecycleServiceCollection'

#  ##################################
#  ## post_persist
#  ##################################
#  Ivoz\Provider\Domain\Service\Domain\UpdateByBrand:
#    tags:
#      - { name: provider.lifecycle.brand.post_persist, priority: 10 }
#
#  Ivoz\Provider\Domain\Service\RoutingPattern\UpdateByBrand:
#    tags:
#      - { name: provider.lifecycle.brand.post_persist, priority: 20 }
#
#  Ivoz\Provider\Domain\Service\Service\UpdateByBrand:
#    tags:
#      - { name: provider.lifecycle.brand.post_persist, priority: 30 }
#
#  ##################################
#  ## post_remove
#  ##################################
#  Ivoz\Provider\Domain\Service\Domain\DeleteByBrand:
#    tags:
#      - { name: provider.lifecycle.brand.post_remove, priority: 10 }
#    arguments: ~
