services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Provider\Domain\Service\Invoice\InvoiceLifecycleServiceCollection:
#    public: true
#
#  provider.lifecycle.invoice.service_collection:
#    '@Ivoz\Provider\Domain\Service\Invoice\InvoiceLifecycleServiceCollection'

#  ##################################
#  ## pre_persist
#  ##################################
#  Ivoz\Provider\Domain\Service\Invoice\CheckValidity:
#    tags:
#      - { name: provider.lifecycle.invoice.pre_persist, priority: 10 }
#
#  ##################################
#  ## commit
#  ##################################
#  Ivoz\Provider\Domain\Service\Invoice\SendGenerateOrder:
#    tags:
#      - { name: provider.lifecycle.invoice.on_commit, priority: 10 }
