services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## on_commit
  ##################################
  Ivoz\Provider\Infrastructure\Domain\Service\PeeringContract\SendTrunksLcrReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $trunksLcrReload:
        '@XmlRpc\XmlRpcTrunksRequest::LcrReload'

  Ivoz\Provider\Infrastructure\Domain\Service\PeeringContract\SendTrunksUacRegReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $trunksUacRegReload:
        '@XmlRpc\XmlRpcTrunksRequest::UacRegReload'