services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## post_persist
  ##################################
  Ivoz\Ast\Domain\Service\Queue\UpdateByIvozQueue:
    tags: [{ name: 'domain.service'}]
    arguments:
      $storagePathResolver:
        '@Service\CommonStoragePathResolver::LocutionEncodedFile'