services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## post_persist
  ##################################
  Ivoz\Provider\Domain\Service\TerminalModel\PersistTemplates:
    tags: [{ name: 'domain.service'}]
    arguments:
      $localStoragePath: '%local_storage_path%'
