services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Provider\Domain\Service\Terminal\TerminalLifecycleServiceCollection:
#    public: true
#
#  provider.lifecycle.terminal.service_collection:
#    '@Ivoz\Provider\Domain\Service\Terminal\TerminalLifecycleServiceCollection'

#  ##################################
#  ## post_persist
#  ##################################
#  Ivoz\Ast\Domain\Service\PsEndpoint\UpdateByTerminal:
#    tags:
#      - { name: provider.lifecycle.terminal.post_persist, priority: 10 }
