services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## error_handler
  ##################################
  Ivoz\Provider\Domain\Service\User\PersistErrorHandler:
    tags:
      - { name: provider.lifecycle.user.error_handler, priority: 10 }
    arguments: ~
