imports:
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/application_server.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/domain.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/outgoing_routing.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/peering_contract.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/peer_server.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/queue.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/routing_pattern_group.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/routing_pattern.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/terminal_model.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/transformation_rule_set.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/transformation_rule.yml" }
  - { resource: "@CoreBundle/Resources/config/lifecycle/provider/user.yml" }

services:
  _defaults:
    autowire: true
    public: false
