services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Provider\Domain\Service\RoutingPatternGroupsRelPattern\CreateAndPersist: ~

  Ivoz\Provider\Domain\Service\RoutingPatternGroup\UpdateByRoutingPatternAndCountry: ~

  Ivoz\Provider\Domain\Service\LcrRule\CreateByOutgoingRoutingAndRoutingPattern: ~

  Ivoz\Provider\Domain\Service\Invoice\Generator:
    arguments:
      $logger: '@logger'
      $vendorDir: '%kernel.root_dir%/../vendor/'
