services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Kam\Domain\Service\TrunksUacreg\TrunksUacregLifecycleServiceCollection:
#    public: true
#
#  kam.lifecycle.trunks_uacreg.service_collection:
#    '@Ivoz\Kam\Domain\Service\TrunksUacreg\TrunksUacregLifecycleServiceCollection'
##
#  ##################################
#  ## on_commit
#  ##################################
  Ivoz\Kam\Infrastructure\Domain\Service\TrunksUacreg\SendTrunksUacRegReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $trunksUacRegReload:
        '@XmlRpc\XmlRpcTrunksRequest::UacRegReload'
