services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## on_commit
  ##################################
  Ivoz\Kam\Infrastructure\Domain\Service\Trusted\SendUsersPermissionsReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $usersPermissionsReload:
        '@XmlRpc\XmlRpcUsersRequest::PermissionsTrustedReload'

  Ivoz\Kam\Infrastructure\Domain\Service\Trusted\SendTrunksPermissionsReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $trunksPermissionsReload:
        '@XmlRpc\XmlRpcTrunksRequest::PermissionsTrustedReload'
