services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## on_commit
  ##################################
  Ivoz\Kam\Infrastructure\Domain\Service\UsersAddress\SendUsersPermissionsReloadRequest:
    tags: [{ name: 'domain.service'}]
    arguments:
      $usersPermissionsReload:
        '@XmlRpc\XmlRpcUsersRequest::PermissionsTrustedReload'
