services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
  Ivoz\Cgr\Domain\Service\RatingPlan\RatingPlanLifecycleServiceCollection:
    public: true

  cgr.lifecycle.rating_plan.service_collection:
    '@Ivoz\Cgr\Domain\Service\RatingPlan\RatingPlanLifecycleServiceCollection'

#  ##################################
#  ## post_persist
#  ##################################
#  Ivoz\Cgr\Domain\Service\RatingPlan\UpdateRatingPlanTag:
#    tags:
#      - { name: cgr.lifecycle.rating_plan.post_persist, priority: 10}
#
#  ##################################
#  ## on_commit
#  ##################################
#  Ivoz\Cgr\Domain\Service\RatingPlan\UpdatedRatingPlanNotificator:
#    tags:
#      - { name: cgr.lifecycle.rating_plan.on_commit, priority: 10}
