services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Cgr\Domain\Service\TpAccountAction\TpAccountActionLifecycleServiceCollection:
#    public: true
#
#  cgr.lifecycle.tp_account_action.service_collection:
#    '@Ivoz\Cgr\Domain\Service\TpAccountAction\TpAccountActionLifecycleServiceCollection'

  ##################################
  ## on_commit
  ##################################
#  Ivoz\Cgr\Domain\Service\TpAccountAction\UpdatedTpAccountActionNotificator:
#    tags:
#      - { name: cgr.lifecycle.tp_account_action.on_commit, priority: 10}


