services:
  _defaults:
    autowire: true
    public: false

  ##################################
  ## Service collection
  ##################################
#  Ivoz\Cgr\Domain\Service\TpRatingProfile\TpRatingProfileLifecycleServiceCollection:
#    public: true
#
#  cgr.lifecycle.tp_rating_profile.service_collection:
#    '@Ivoz\Cgr\Domain\Service\TpRatingProfile\TpRatingProfileLifecycleServiceCollection'

#  ##################################
#  ## pre_persist
#  ##################################
#  Ivoz\Cgr\Domain\Service\TpRatingProfile\UpdateRatingProfileTag:
#    tags:
#      - { name: cgr.lifecycle.tp_rating_profile.pre_persist, priority: 10}
#
#  ##################################
#  ## on_commit
#  ##################################
#  Ivoz\Cgr\Domain\Service\TpRatingProfile\UpdatedTpRatingProfileNotificator:
#    tags:
#      - { name: cgr.lifecycle.tp_rating_profile.on_commit, priority: 10}
